apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: notification-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5006

          env:
            - name: PORT
              value: "5006"

            - name: HOST
              value: "0.0.0.0"

            # ✅ مهم بزاف: Pod IP
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP

            - name: EUREKA_HOST
              value: "discovery-service"

            - name: EUREKA_PORT
              value: "8761"

            - name: DB_HOST
              value: "mongodb"

            - name: DB_PORT
              value: "27017"

            - name: DB_NAME
              value: "notification_db"

            - name: KAFKA_BROKER
              value: "kafka:9092"

            - name: EMAIL_USER
              value: "qriblik7@gmail.com"

            - name: EMAIL_PASS
              value: "vajr icgk kqid hhnw"

          readinessProbe:
            tcpSocket:
              port: 5006
            initialDelaySeconds: 30
            periodSeconds: 10

          livenessProbe:
            tcpSocket:
              port: 5006
            initialDelaySeconds: 60
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  selector:
    app: notification-service
  ports:
    - protocol: TCP
      port: 5006
      targetPort: 5006
  type: ClusterIP