apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-service
  namespace: default
  labels:
    app: discovery-service
    project: qrib-lik
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-service
  template:
    metadata:
      labels:
        app: discovery-service
    spec:
      containers:
        - name: discovery-service
          image: discovery-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8761


          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 40
            periodSeconds: 20

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 30
            periodSeconds: 10

          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
            - name: SERVER_PORT
              value: "8761"
            - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
              value: "false"
            - name: EUREKA_CLIENT_FETCH_REGISTRY
              value: "false"

---
apiVersion: v1
kind: Service
metadata:
  name: discovery-service
spec:
  type: LoadBalancer
  selector:
    app: discovery-service
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761