spring.application.name=Configuration-Service
server.port=9999
spring.cloud.config.server.git.uri=https://github.com/zahrahiu/Delivery_projet.git
spring.cloud.config.server.git.search-paths=config-lab-repo
spring.cloud.config.server.git.default-label=main
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.instance-id=${spring.application.name}:${server.port}




# expose ??? ??? endpoints ?????????
management.endpoints.web.exposure.include=health,info,metrics,prometheus

# ??????? ??????? ?? Spring Boot 3 (????? .enabled ?????? ?? .step)
management.prometheus.metrics.export.enabled=true

# ??? ???? ???????? ????? (???? ?? Grafana)
management.endpoint.prometheus.enabled=true
management.endpoint.health.show-details=always
