spring.application.name=Configuration-Service
server.port=9999
spring.cloud.config.server.git.uri=https://github.com/zahrahiu/Delivery_projet.git
spring.cloud.config.server.git.search-paths=config-lab-repo
spring.cloud.config.server.git.default-label=main
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/