spring.application.name=parcel-service


spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer


spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

eureka.instance.instance-id=${spring.application.name}:${server.port}

spring.cloud.bootstrap.enabled=true


spring.cloud.config.fail-fast=false
spring.cloud.config.enabled=true
spring.config.import=optional:configserver:http://configuration-service:9999

# ??? ???? Zipkin ?? Kubernetes
management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans

# ???? ???? ??????? ????? ????? (1.0 ???? 100%? ?????? ???????)
management.tracing.sampling.probability=1.0

# ??? ????????? ?????? ?? ??? Logs (??????? ???? ?????)
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]

# expose ??? ??? endpoints ?????????
management.endpoints.web.exposure.include=health,info,metrics,prometheus

# ??????? ??????? ?? Spring Boot 3 (????? .enabled ?????? ?? .step)
management.prometheus.metrics.export.enabled=true

# ??? ???? ???????? ????? (???? ?? Grafana)
management.endpoint.prometheus.enabled=true
management.endpoint.health.show-details=always


#server.port=8082
#spring.datasource.url=jdbc:postgresql://localhost:5432/delivery_db_parcels
#spring.datasource.username=postgres
#spring.datasource.password=zahra123
#
#spring.jpa.hibernate.ddl-auto=update
#rsa.publickey=classpath:keys/publicKey.pem
#rsa.privatekey=classpath:keys/privateKey.pem
#
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
#eureka.instance.prefer-ip-address=true
#spring.cloud.discovery.enabled=true

# Kafka Config
#spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
#spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
#spring.kafka.consumer.properties.spring.json.trusted.packages=*




###########
