spring.application.name=parcel-service
server.port=8082
spring.datasource.url=jdbc:postgresql://localhost:5432/delivery_db_parcels
spring.datasource.username=postgres
spring.datasource.password=zahra123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

eureka.instance.instance-id=${spring.application.name}:${server.port}

rsa.publickey=classpath:keys/publicKey.pem
rsa.privatekey=classpath:keys/privateKey.pem

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
spring.cloud.discovery.enabled=true

# Kafka Config
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer