server.port=8888
spring.application.name=gateway-service

# Eureka Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.instance.instance-id=${spring.application.name}:${server.port}

# Enable Discovery
spring.cloud.discovery.enabled=true

# RSA Keys
rsa.public-key=classpath:keys/publicKey.pem
rsa.private-key=classpath:keys/privateKey.pem

# Dynamic Routing Settings
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true