apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-service
  template:
    metadata:
      labels:
        app: users-service

      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8081"  # البورت اللي خدام فيه هاد السيرفيس
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
        - name: users-service
          image: users-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
            - name: SPRING_APPLICATION_NAME
              value: "users-service"
            - name: SERVER_PORT
              value: "8081"

            # تفعيل الـ Config Client باش يجيب الـ RSA من الـ Repo
            - name: SPRING_CLOUD_CONFIG_ENABLED
              value: "true"
            - name: SPRING_CLOUD_CONFIG_URI
              value: "http://configuration-service:9999"

            # مهم لـ Spring Boot 3 لضمان الاتصال بـ Config Server فـ الديماراج
            - name: SPRING_CONFIG_IMPORT
              value: "optional:configserver:http://configuration-service:9999"

            # إعدادات الداتابيز
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-service:5432/delivery_db_users"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "zahra123"
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "update"

            # إعدادات Eureka و Kafka (تأكدي من أسماء الـ Services)
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://discovery-service:8761/eureka/"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"

          # عطينا وقت كافي للسيرفيس باش يلقى الـ Config ويقرا الـ Keys
          readinessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 120
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 180
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  selector:
    app: users-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP