apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracking-service
  namespace: default
  labels:
    app: tracking-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tracking-service
  template:
    metadata:
      labels:
        app: tracking-service
    spec:
      containers:
        - name: tracking-service
          image: tracking-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8085
          env:
            - name: PORT
              value: "8085"
            - name: INSTANCE_HOST
              value: "tracking-service"
            - name: EUREKA_HOST
              value: "discovery-service"
            - name: EUREKA_PORT
              value: "8761"
            - name: DB_HOST
              value: "mongodb"
            - name: DB_PORT
              value: "27017"
            - name: KAFKA_BROKER
              value: "kafka-service:9092"
          readinessProbe:
            tcpSocket:
              port: 8085
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8085
            initialDelaySeconds: 60
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: tracking-service
spec:
  selector:
    app: tracking-service
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
  type: ClusterIP