# Eureka Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
spring.cloud.discovery.enabled=true

# Kafka Configuration
spring.kafka.bootstrap-servers=localhost:9092

# RSA Keys
rsa.publickey=classpath:keys/publicKey.pem
rsa.privatekey=classpath:keys/privateKey.pem