spring.application.name=service-security
eureka.instance.instance-id=${spring.application.name}:${server.port}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Force localhost ??? IP
eureka.instance.hostname=localhost
logging.level.org.gym.service_security=DEBUG
spring.cloud.config.enabled=true
spring.config.import=optional:configserver:http://configuration-service:9999
spring.jpa.hibernate.ddl-auto=update
management.endpoint.health.show-details=always
management.info.env.enabled=true

# ??? ???? Zipkin ?? Kubernetes
management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans

# ???? ???? ??????? ????? ????? (1.0 ???? 100%? ?????? ???????)
management.tracing.sampling.probability=1.0

# ??? ????????? ?????? ?? ??? Logs (??????? ???? ?????)
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]


# expose ??? ??? endpoints ?????????
management.endpoints.web.exposure.include=health,info,metrics,prometheus

# ??????? ??????? ?? Spring Boot 3 (????? .enabled ?????? ?? .step)
management.prometheus.metrics.export.enabled=true

# ??? ???? ???????? ????? (???? ?? Grafana)
management.endpoint.prometheus.enabled=true
# Eureka
eureka.client.service-url.defaultZone=http://discovery-service:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.lease-renewal-interval-in-seconds=30
eureka.instance.lease-expiration-duration-in-seconds=90
rsa.public-key=classpath:keys/publicKey.pem
rsa.private-key=classpath:keys/privateKey.pem

logging.level.com.netflix.discovery=DEBUG


# Logging Spring Security
#logging.level.org.springframework.security=DEBUG
# Logging
# Disable config server
#spring.cloud.discovery.enabled=true
#spring.jpa.hibernate.ddl-auto=update
#eureka.instance.prefer-ip-address=false
#spring.datasource.url=jdbc:postgresql://localhost:5432/delivery_db
#spring.datasource.username=postgres
#spring.datasource.password=zahra123
#server.port=8080
#eureka.client.service-url.defaultZone=${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka}
# Actuator (mohim bach Eureka y9ra health)
