spring.application.name=service_security
spring.datasource.url=jdbc:postgresql://localhost:5432/delivery_db
spring.datasource.username=postgres
spring.datasource.password=zahra123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


rsa.publickey=classpath:keys/publicKey.pem
rsa.privatekey=classpath:keys/privateKey.pem

# Logging Spring Security
logging.level.org.springframework.security=DEBUG
logging.level.org.gym.service_security=DEBUG