spring.application.name=service-security
eureka.instance.instance-id=${spring.application.name}:${server.port}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Force localhost ??? IP
eureka.instance.hostname=localhost
logging.level.org.gym.service_security=DEBUG
spring.cloud.config.enabled=true
spring.config.import=optional:configserver:http://localhost:9999
management.endpoints.web.exposure.include=*

#spring.datasource.url=jdbc:postgresql://localhost:5432/delivery_db
#spring.datasource.username=postgres
#spring.datasource.password=zahra123
#server.port=8080
#eureka.client.service-url.defaultZone=${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka}

#spring.cloud.discovery.enabled=true
#spring.jpa.hibernate.ddl-auto=update



#eureka.instance.prefer-ip-address=false

#rsa.publickey=classpath:keys/publicKey.pem
#rsa.privatekey=classpath:keys/privateKey.pem

# Logging Spring Security
#logging.level.org.springframework.security=DEBUG



