spring.application.name=users-service
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ? ????? Config Server
spring.cloud.config.enabled=true
spring.config.import=optional:configserver:http://configuration-service:9999

# ? Eureka (???? ????? ??? ?? ?????? ?? Config Server)
eureka.client.serviceUrl.defaultZone=http://discovery-service:8761/eureka/
eureka.instance.instance-id=${spring.application.name}:${server.port}

# ? Logging
spring.jpa.hibernate.ddl-auto=update
logging.level.org.delivery.users_service=DEBUG
logging.level.com.netflix.discovery=DEBUG

# ??? ???? Zipkin ?? Kubernetes
management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans

# ???? ???? ??????? ????? ????? (1.0 ???? 100%? ?????? ???????)
management.tracing.sampling.probability=1.0

# ??? ????????? ?????? ?? ??? Logs (??????? ???? ?????)
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]

# expose ??? ??? endpoints ?????????
management.endpoints.web.exposure.include=health,info,metrics,prometheus

# ??????? ??????? ?? Spring Boot 3 (????? .enabled ?????? ?? .step)
management.prometheus.metrics.export.enabled=true

# ??? ???? ???????? ????? (???? ?? Grafana)
management.endpoint.prometheus.enabled=true
management.endpoint.health.show-details=always
# Eureka will use env variables
#server.port=8081
#spring.datasource.url=jdbc:postgresql://localhost:5432/delivery_db_users
#spring.datasource.username=postgres
#spring.datasource.password=zahra123
#
#spring.cloud.discovery.enabled=true
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
#eureka.instance.prefer-ip-address=true

#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
# Upload directory
#upload.directory=Users_Service/uploads/
#spring.kafka.bootstrap-servers=localhost:9092
#rsa.publickey=classpath:keys/publicKey.pem
#rsa.privatekey=classpath:keys/privateKey.pem






